### ISSUE TITLE
Problem with rdtsc diff using vmexit

### ISSUE THREAD

**Issue by fabinet** [LordNoteworthy/al-khaser#77] opened 2017-05-11 15:03 UTC
I think there is a problem with your RDTSC diff using VMEXIT.
Pafish detects my VM using this trick but not al-khaser.
I think this is due to the missing 500 ms sleep present in the pafish one : 
for (i = 0; i < 10; i++) {
		avg = avg + rdtsc_diff_vmexit();
		Sleep(500);
}

**Comment by LordNoteworthy** [comment] 2017-07-06 20:05
I will check that and get back to you, sorry for my late answer.

**Comment by LordNoteworthy** [comment] 2017-09-07 17:14
back to you again,  sorry.

Which virtual machine you are using (vmware, vbox)?

**Comment by fabinet** [comment] 2017-11-23 08:48
KVM

**Comment by mauronz** [comment] 2018-02-01 10:48
The problem is that visual studio does not compile correctly __cpuid(...) in that function. It just skips it.
To solve it put cpuid as inline assembly:

__asm {
xor eax, eax
cpuid
}
![vmexit](https://user-images.githubusercontent.com/19782194/35674673-b5bda236-0745-11e8-8c6b-3c3da152d9f6.jpg)

**Comment by LordNoteworthy** [comment] 2018-02-01 19:13
Oh because I guess the compiler see that we dont make use of cpuid return data and he ignored it. Nice finding ! I will see if I can disable optimization or force the compiler to keep the cpuid otherwise I will inline it. Thanks a lot !!

**Comment by LordNoteworthy** [comment] 2018-02-28 19:33
@fabinet can you check now ?

**Comment by fabinet** [comment] 2018-03-01 12:57
Well, it's working now, nice one :+1: @mauronz  @LordNoteworthy 
--> Do you have any idea on how to "patch" RDTSC in order to bypass this trick?

**Comment by LordNoteworthy** [comment] 2018-03-08 17:35
I will close this issue, if  you have any issues, feel free to open it again :)

**Closed by LordNoteworthy** 2018-03-08 17:35 UTC
Labels: bug
